edition = "2021"
max_width = 120
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Max"
fn_call_width = 80
attr_fn_like_width = 100
array_width = 100
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
